version: "3.0"
services:
  ms_srtv:
    command: npm start
    container_name: ms_srtv
    image: ms_srtv
    environment:
      - PORT=3000
      - EXPIRED=30
      - ROUND_TO_HASH=10
      - NODE_ENV=development
      - SECRET_KEY=jPRmGnpa6M
      - PROJECT_ID=strv-addressbook-gonzale-25cc5
      - API_KEY=AIzaSyBT8yOKjmodZMAyalxV_ScKqMU-yAA4SaY
      - DATABASE_URL_DEV=mongodb://172.17.0.1:27017/users
      - FIREBASE_NAME_PROJECT=strv-addressbook-gonzalez-fran
      - DATABASE_URL_TEST=mongodb://192.241.145.208:27017/users
      - AUTH_DOMAIN=strv-addressbook-gonzale-25cc5.firebaseapp.com    
      - FIRE_BASE_DATABASE_URL=https://strv-addressbook-gonzale-25cc5-default-rtdb.firebaseio.com/
      - CLIENT_EMAIL=firebase-adminsdk-k8ckl@strv-addressbook-gonzale-25cc5.iam.gserviceaccount.com
      - DATABASE_URL_PROD=mongodb+srv://eco_user:yXhqqMbLhx8uK18d@ecocluster.9pxzx.mongodb.net/media_info?retryWrites=true&w=majority
      - PRIVATE_KEY=-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCzRbu2cAVTu0Yi\nRReYZ6KEvaPmz1b88vOe+2rSRUMp+LL/+As+WxpKh5B8DNoIOKnT9RZlNM/UZkXg\nMqvhYKwS23LgPuu8l3aOCp3ruadIkENAEUrWYe+0FLA0EGJLBdkVDFXZhbidL4Tv\nnEL6+XqdfV0Bt9DCmz+4+Kj7BWWjcfWRvgK9vdWeQxgAwQaA2+2+hY8fY4QeNHL2\nVjqiYjpOPPf6sDNfb7YakRwEu0mLTFaL/KlwIWXC1Dq4wSvB5XheoBTimf3QGMRq\nTl+FnjxLJ7kAKKl5+4JbbsPiBxDW2HCWP9IKxnkLAWYHLFkve8eppMvz57nR9eTg\nkUiDDiJpAgMBAAECgf9w2U5DyY0qgcV95rOAfIkRUujNCJ4stilYkQTtPpLI5bgu\ngs9d5HtOu+3eKNJ9c/qm/xQNIVflnEh5zDizGhrRKmyZCWkOwa/sOg97rTv6GAkK\nJQu3AaKikvzxyStJ9QrYKEVIzteOGuhtUzA9GRs8u22Qmn7cAff0hPlz12UW1qOI\nV+ckn17IqEJkYWu8TY0GdJpeMY2XD/kGKiPmrIZuzfQfEFa0qvkjD10H7DlWTxrT\nMguQSOVFabK5kODwZLnCYUpVSeqkzEDWX5KpYUgxCYAX4SbcanawrCxD1AOfilHl\nEIb7G8MnhfV+GEPDhai5a4/1wJs71xojwu7Fgt0CgYEA6+WZ1P3c25f7cgD3/NnT\nIu7/XAfqUbaQCISVmU1Js1Mld15O9CF+/9ImBFDiDlbkzjZABwpczWjurI1uRPCD\nWcx/zaGpKCAYbA+JdITGkwnXeVMuoWhErbiy9fZ3w1inoIou6KOa2TR8tw0EU/7W\n3gUaVWwqf6wtU3Si9OYtFHUCgYEAwozLjxJdgBc7517Mbr15mmTC6wMlIKOB1/+i\nBvoMLJRsHa45Rzu0snZvOOsS45QkvtlFYRekQLtDaO+6yg6CL3wdf7TwwXX+wuR0\n/vbAFLA+3dml2DBELN8ze7sbNeZ5V6gClFd3VMHPZ7RAthCnvF+1dJN4p2J5AKd7\nMsGVx6UCgYEA3Uh7Hm6pUCDokU/RURJwWdPCHW2bY92SjTr6Ll1u5lX3zlrcS2xk\nesuCOAg7leHzLnF7bF9PIKzvP1RIfUj0njcUKCwexvIclrmYYoHu2J2h0EC0fFqY\nGjIpRktWmxu92v3k9PwL1PbEit4eEkD7BDfbNQiLcUptFl1SQ9LrtMUCgYEAikvB\nq/uXIaXifG9kDVh9Z+Y2tQ7wRopUk7HxgNog61O6o0KlDuD/a1lLaP+Z1tMJZ+1V\nJ1bB+Q3lNmQruNSlcJHe+lgqSKvTJMF39YJ8Oniqx9Oe09ZDsE4d79eq2R7zpP8W\njlK6zjJTeFmnIoUmZ371o1/thbc3YuKrbgI0sc0CgYANWJLXoYaT80N8qR0RYPr6\nwBzqLybmQbs5njWtKQpZNiEbfqjCPSNETLcgx+ide50cZAz2D2kVq83hawTdJyGO\nLNSz9ww87gufVElNkLnCH5bpabyXhu0KVAQC2DvTRe6O6f+X5uki6Xo6ebgMKYa0\nEWlfHUpptmvzxCpXXCp1pQ==\n-----END PRIVATE KEY-----\n
    ports:
      - "3000:3000"
    volumes:  
      - ./strv-project:/app
    restart: unless-stopped

  mongo:
    image: mongo
    restart: always
    volumes:  
      - ./mongo-volume:/data/db

volumes:
  ms_srtv: