require('dotenv').config();

module.exports = {
    ROUND_TO_HASH: 10, //number to be able to hash password
    EXPIRED: process.env.EXPIRED, //time the token is active
    PORT: process.env.PORT, //port's number what should the server listen to
    DATABASE_URL_PROD: process.env.DATABASE_URL_PROD, //mongo atlas link to connect to the database
    DATABASE_URL_DEV: process.env.DATABASE_URL_DEV, //mongo atlas link to connect to the database
    NODE_ENV: process.env.NODE_ENV, //environment of the project
    FIRE_BASE_DATABASE_URL: process.env.FIRE_BASE_DATABASE_URL,
    API_KEY: process.env.API_KEY, // apiKey that is generated by firebase
    AUTH_DOMAIN: process.env.AUTH_DOMAIN, // domain that is generated by firebase
    SECRET_KEY: process.env.SECRET_KEY, //random alphanumeric string to encode and decode token
    FIREBASE_NAME_PROJECT: process.env.FIREBASE_NAME_PROJECT,
    PROJECT_ID: process.env.PROJECT_ID, //project id from firebase
    CLIENT_EMAIL: process.env.CLIENT_EMAIL, //email client from firebase
    PRIVATE_KEY: process.env.PRIVATE_KEY.replace(/\\n/g, '\n'),
}